import Navigation from '@/components/Navigation'
import './globals.css'

export const metadata = {
  title: 'Mi proyecto',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <Navigation/>
        {children}
      </body>
    </html>
  )
}
